services:
  - type: web
    name: rbuilder
    env: docker
    plan: free
    dockerfilePath: Dockerfile
    envVars:
      - key: PORT
        value: 3000
      - key: APP_URL
        sync: false
      - key: DATABASE_URL
        sync: false
      - key: AUTH_SECRET
        generateValue: true
